[package]
name = "asteroidroulette"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jgke@jgke.fi>"]
edition = "2018"

[dependencies]
rand = "0.6.1"

[lib]
name = "asteroidroulette_lib"
path = "src/lib.rs"

[[bin]]
name = "asteroidroulette"
path = "src/main.rs"
